core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include("masjidConfig.urls")),
    path('', include("posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

posts/urls.py
from django.urls import path, include

from . import views
from .views import get_month_tbl
app_name = 'posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('monthly_times/', views.month_view, name='month_view'),
    path('post/<int:id>/', views.post_view, name='post_view'),
    path('posts-admin', views.posts_admin, name='posts_admin'),
    path('posts', views.post_list_view, name='post_list'),
    path('create_post', views.post_form, name='post_form'),
    path('post/<int:id>/delete/', views.delete_post, name='delete_post'),
    path('post/<int:id>/toggle', views.hide_post_toggle, name='post_toggle'),
    path('post/edit/<int:id>/', views.edit_post_form, name='post_edit'),
    path('pdf', views.GeneratePdf.as_view(), name="pdf"),
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import os

# Create your models here.
POST_CHOICES = [
    ('News', 'News'),
    ('Events', 'Events'),
    
]

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=1000) # RichTextField()
    type = models.CharField(max_length=200, choices=POST_CHOICES)
    published = models.BooleanField(default=False)
    published_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to='images/',
        processors=[ResizeToFill(800, 450)],
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.title
    
    def get_image_url(self):
        """Returns the image URL or falls back to default static image"""
        if self.image:
            return self.image.url
        return os.path.join(settings.STATIC_URL, 'images/default_image.jpg')

    def get_absolute_url(self, id=id or None):
        return reverse("posts:post_view", kwargs={'id':self.id})

posts/forms.py
from django.forms import ModelForm,widgets
from django.forms.widgets import TextInput, EmailInput
from .models import *
from django import forms


class PostForm(forms.ModelForm):
    content = forms.CharField() # widget=CKEditorWidget()
    class Meta:
        model = Post
        fields = '__all__'
    
    

posts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.views.generic import View 
from django.template.loader import get_template
from functools import lru_cache

from .utils import render_to_pdf

import requests, json, datetime
from .forms import PostForm
from .models import Post

from masjidConfig.models import CentreProfile

'''This function is used to round the time UP to the nearest 5,10,15
For more info, the idea is taken from 
https://stackoverflow.com/questions/13071384/ceil-a-datetime-to-next-quarter-of-an-hour
'''
def ceil_dt(dt, delta):
    return dt + (datetime.datetime.min - dt) % delta

''' The Jamaah Calculator function takes the desired "minutes after" from the masjid 
profile and adjusts the jamaah times accordingly by using Pythons datetime library.
'''
def jamaah_calculator(azaanTime, minutesAfter):

    if minutesAfter == "5":
        return datetime.datetime.strptime(azaanTime, '%H:%M') + datetime.timedelta(minutes = 5)
    elif minutesAfter == "10":
        return datetime.datetime.strptime(azaanTime, '%H:%M') + datetime.timedelta(minutes = 10)
    elif minutesAfter == "15":
        return datetime.datetime.strptime(azaanTime, '%H:%M') + datetime.timedelta(minutes = 15)
    elif minutesAfter == "round_to_fifteen":
        return ceil_dt(datetime.datetime.strptime(azaanTime, '%H:%M'), datetime.timedelta(minutes=15))
    else:
        return ceil_dt(datetime.datetime.strptime(azaanTime, '%H:%M'), datetime.timedelta(minutes=30))


@lru_cache(maxsize=1)
def get_masjid_data():
    masjid = CentreProfile.load()
    #### Variables loaded from centre profile here #####
    masjid_name = masjid.masjid_Name
    city = masjid.city 
    country = masjid.country 
    method = masjid.method
    longitude = masjid.longitude
    latitude = masjid.latitude
    current_time = datetime.datetime.now()
    month = current_time.month
    year = current_time.year
    fajr_jam_min = masjid.fajr_jamaah_minutes
    dh_jam_min = masjid.dhuhr_jamaah_minutes
    asr_jamaah_minutes = masjid.asr_jamaah_minutes
    maghrib_jamaah_minutes = masjid.maghrib_jamaah_minutes
    isha_jamaah_minutes = masjid.isha_jamaah_minutes
    return masjid, masjid_name,city, country, method, longitude, latitude, current_time, month, year, fajr_jam_min,dh_jam_min, asr_jamaah_minutes, maghrib_jamaah_minutes,isha_jamaah_minutes

# NOTE:
# Ternary statements below solves minutes being displayed as single digit eg
# 17:05 displaying as 17:5 or 20:00 displaying as 20:0
def home(request):
    # Collecting masjid data from class
    masjid, masjid_name,city, country, method, longitude, latitude, current_time, month, year, fajr_jam_min,dh_jam_min, asr_jamaah_minutes, maghrib_jamaah_minutes,isha_jamaah_minutes = get_masjid_data()
    ###############################################
    posts = Post.objects.all().filter(published=True)
    
    api_data = requests.get(f'http://api.aladhan.com/v1/timingsByCity?city={city}&country={country}&method={method}')
    d = api_data.json()
    fajr = d['data']['timings']['Fajr']
    fj = jamaah_calculator(fajr, fajr_jam_min)
    fjmins = f"{fj.minute}" if len(str(fj.minute))==2 else f"0{fj.minute}"
    fajr_j = f"{fj.hour}:{fjmins}"
    sunrise = d['data']['timings']['Sunrise']
    dhuhr = d['data']['timings']['Dhuhr']
    dh = jamaah_calculator(dhuhr, dh_jam_min)
    dhmins = f"{dh.minute}" if len(str(dh.minute))==2 else f"0{dh.minute}"
    dhuhr_j = f"{dh.hour}:{dhmins}"
    asr = d['data']['timings']['Asr']
    asrj = jamaah_calculator(asr, asr_jamaah_minutes)
    asmins = f"{asrj.minute}" if len(str(asrj.minute))==2 else f"0{asrj.minute}"
    asr_j= f"{asrj.hour}:{asmins}"
    maghrib = d['data']['timings']['Maghrib']
    mg = jamaah_calculator(maghrib, maghrib_jamaah_minutes)
    mgmins = f"{mg.minute}" if len(str(mg.minute))==2 else f"0{mg.minute}"
    maghrib_j =  f"{mg.hour}:{mgmins}"
    isha = d['data']['timings']['Isha']
    ish = jamaah_calculator(isha, isha_jamaah_minutes)
    ismins = f"{ish.minute}" if len(str(ish.minute))==2 else f"0{ish.minute}"
    isha_j= f"{ish.hour}:{ismins}"
    today = d['data']['date']['readable']
    hijri = f"{d['data']['date']['hijri']['day']}-{d['data']['date']['hijri']['month']['en']}-{d['data']['date']['hijri']['year']}"
    
    # Get today's day name (lowercase)
    today_day = current_time.strftime('%A').lower()
    weekly_schedule = masjid.weekly_schedule
    today_schedule = weekly_schedule.get(today_day, {
        'open': True,
        'fajr_jamaah': True,
        'dhuhr_jamaah': True,
        'asr_jamaah': True,
        'maghrib_jamaah': True,
        'isha_jamaah': True
    })
    
    context = {'masjid':masjid, 'posts':posts, 'fajr_j':fajr_j, 'dhuhr_j':dhuhr_j, 'asr_j':asr_j, 'maghrib_j':maghrib_j, 'isha_j':isha_j,
        'fajr':fajr,'sunrise':sunrise, 'dhuhr':dhuhr, 'asr':asr, 'maghrib':maghrib, 'isha':isha, 'today':today, 'hijri':hijri,
        'today_day':today_day, 'weekly_schedule':weekly_schedule, 'today_schedule':today_schedule}
    
    return render(request, 'posts/home.html', context)

def get_month_tbl():
    # Collecting masjid data from class
    masjid, masjid_name,city, country, method, longitude, latitude, current_time, month, year, fajr_jam_min,dh_jam_min, asr_jamaah_minutes, maghrib_jamaah_minutes,isha_jamaah_minutes = get_masjid_data()
    ###############################################
    month_api = requests.get(f'http://api.aladhan.com/v1/calendar?latitude={latitude}&longitude={longitude}&country={country}&method={method}&month={month}&year={year}')

    # Check if the request was successful
    if month_api.status_code != 200:
        raise Exception(f"API request failed with status code {month_api.status_code}")
    
    data = month_api.json()
    d = data['data']
    month_data = []
    weekly_schedule = masjid.weekly_schedule
    
    for row in d:
        date = row["date"]["gregorian"]["date"]
        weekday = row["date"]["gregorian"]["weekday"]["en"]
        weekday_lower = weekday.lower()
        mon = row["date"]["gregorian"]["month"]["en"]
        
        # Check if centre is open on this day
        day_schedule = weekly_schedule.get(weekday_lower, {})
        is_day_open = day_schedule.get('open', True)
        
        fajr = row["timings"]["Fajr"][0:5]
        sunrise = row["timings"]["Sunrise"][0:5]
        fj = jamaah_calculator(fajr, fajr_jam_min)
        fjmins = f"{fj.minute}" if len(str(fj.minute))==2 else f"0{fj.minute}"
        fajr_j = f"{fj.hour}:{fjmins}"
        
        dhuhr = row["timings"]["Dhuhr"][0:5]
        dh = jamaah_calculator(dhuhr, dh_jam_min)
        dhmins = f"{dh.minute}" if len(str(dh.minute))==2 else f"0{dh.minute}"
        dhuhr_j = f"{dh.hour}:{dhmins}"
        
        asr = row["timings"]["Asr"][0:5]
        asrj = jamaah_calculator(asr, asr_jamaah_minutes)
        asmins = f"{asrj.minute}" if len(str(asrj.minute))==2 else f"0{asrj.minute}"
        asr_j= f"{asrj.hour}:{asmins}"
        
        maghrib = row["timings"]["Maghrib"][0:5]
        mg = jamaah_calculator(maghrib, maghrib_jamaah_minutes)
        mgmins = f"{mg.minute}" if len(str(mg.minute))==2 else f"0{mg.minute}"
        maghrib_j =  f"{mg.hour}:{mgmins}"
        
        isha = row["timings"]["Isha"][0:5]
        ish = jamaah_calculator(isha, isha_jamaah_minutes)
        ismins = f"{ish.minute}" if len(str(ish.minute))==2 else f"0{ish.minute}"
        isha_j= f"{ish.hour}:{ismins}"
        
        day_no = row["date"]["gregorian"]["day"]
        day_ab = row["date"]["gregorian"]["weekday"]
        month_data.append({
            'fajr':fajr,'fajr_j':fajr_j,'sunrise':sunrise, 'dhuhr':dhuhr, 'dhuhr_j':dhuhr_j,'asr':asr,'asr_j':asr_j,'maghrib':maghrib,'maghrib_j':maghrib_j, 'isha':isha,'isha_j':isha_j,
            'month':mon, 'date':date, 'weekday':weekday,'day_no':day_no, 'day_ab':day_ab,
            'is_day_open': is_day_open,
            'fajr_jamaah': day_schedule.get('fajr_jamaah', True),
            'dhuhr_jamaah': day_schedule.get('dhuhr_jamaah', True),
            'asr_jamaah': day_schedule.get('asr_jamaah', True),
            'maghrib_jamaah': day_schedule.get('maghrib_jamaah', True),
            'isha_jamaah': day_schedule.get('isha_jamaah', True)
        })
    return month_data

def month_view(request):
    month_data = get_month_tbl()
    current_time = datetime.datetime.now()
    month_name = current_time.strftime("%B")
    year = current_time.year 
    context = {'d':json.dumps(month_data), 'month':month_name, 'year':year}
    return render(request, 'posts/month.html', context)

def post_view(request, id):
    post = Post.objects.get(id=id)
    context = {'post':post}
    return render(request, 'posts/post_view.html', context)

@login_required
def post_form(request): 
    form = PostForm(request.POST, request.FILES) 
    if form.is_valid():
        form.save()
        return redirect('posts:home')
    else:
        form = PostForm()
        context = {'form':form}
        return render(request, 'posts/post_form.html', context)

@login_required
def edit_post_form(request, id):
    post = get_object_or_404(Post, pk=id)
    
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('posts:post_view', kwargs={'id': id}))
        else:
            # Print form errors for debugging
            print("Form errors:", form.errors)
            context = {'form': form, 'post': post}
            return render(request, 'posts/post_edit_form.html', context)
    else:
        form = PostForm(instance=post)
        context = {'form': form, 'post': post}
        return render(request, 'posts/post_edit_form.html', context)

posts/templates/posts/partials/admin-posts-partial.html
{% load static %}
<ul class="list bg-base-100 rounded-box shadow-md"
    id="posts_list"  
    hx-swap="outerHTML swap"
    >
    <li class="p-4 pb-2 text-xxl opacity-60 tracking-wide">Posts</li>
    {% for post in posts %}
        {% include 'posts/partials/single_post.html' %}
    {% endfor %}
</ul>

posts/templates/posts/partials/daily_time.html
{% load static %}
{% load masjid_tags %}
<div>
  <div class="pl-4 pb-2">
    <div class="join items-center place-self-center">
      <small class="join-item pr-1">{{today}}</small> 
      <img class="join-item" src="https://img.icons8.com/color/24/000000/kaaba.png" />
      <small class="join-item pl-1">{{hijri}}</small>
    </div>
  </div>

  {% if today_schedule.open %}
    <!-- Fajr Card -->
    <div class="card md:card-side bg-base-100 shadow-xl max-h-[50px] w-full md:w-[250px] mb-2">
      <!-- Left Side: Image -->
      <figure class="max-w-[50px] max-h-[50px] bg-yellow-400 flex items-center justify-center">
        <img src="{% static 'images/sunrise.png' %}" alt="fajr" class="w-full h-full object-cover" />
      </figure>

      <!-- Right Side: Text Content -->
      <div class="card-body pl-2 pt-1 leading-none">
            
        <span class="flex justify-between">
          <span class="text-sm font-bold">Fajr: <span id="T_Fajr text-xs">{{fajr}}</span></span>
          
          <span class="text-xs">
            <img 
            width="16" 
            src="{% static 'images/sunrise_x16.png' %}" 
            alt="Sunrise" 
            class="inline-block" 
          />
          {{ sunrise }}</span>
        </span>
        {% if today_schedule.fajr_jamaah %}
          <span>Jamaah: {{ fajr_j }}</span>
        {% else %}
          <span>Jamaah: <span class="text-red-500 font-bold">CLOSED</span></span>
        {% endif %}
            
      </div>
    </div>
  {% else %}
    <!-- Fajr Card - Closed -->
    <div class="card md:card-side bg-base-100 shadow-xl max-h-[50px] w-full md:w-[250px] mb-2">
      <!-- Left Side: Image -->
      <figure class="max-w-[50px] max-h-[50px] bg-yellow-400 flex items-center justify-center">
        <img src="{% static 'images/sunrise.png' %}" alt="fajr" class="w-full h-full object-cover" />
      </figure>

      <!-- Right Side: Text Content -->
      <div class="card-body pl-2 pt-1 leading-none">
        <span class="text-sm font-bold">Fajr: <span class="text-red-500 font-bold">CLOSED</span></span>
        <span>Jamaah: <span class="text-red-500 font-bold">CLOSED</span></span>
      </div>
    </div>
  {% endif %}

  <!-- Dhuhr Card -->
  <div class="card md:card-side bg-base-100 shadow-xl max-h-[50px] w-full md:w-[250px] mb-2">
    <!-- Left Side: Image -->
    <figure class="max-w-[50px] max-h-[50px] bg-blue-400 flex items-center justify-center">
      <img src="{% static 'images/sun.png' %}" alt="fajr" class="w-full h-full object-cover" />
    </figure>

    <!-- Right Side: Text Content -->
    <div class="card-body pl-2 pt-1 leading-none">
          
      {% if today_schedule.open %}
        <span class="text-sm font-bold">Dhuhr:<span id="T_Fajr text-xs">{{dhuhr}}</span></span>
        {% if today_schedule.dhuhr_jamaah %}
          <span>Jamaah: {{ dhuhr_j }}</span>
        {% else %}
          <span>Jamaah: <span class="text-red-500 font-bold">CLOSED</span></span>
        {% endif %}
      {% else %}
        <span class="text-sm font-bold">Dhuhr: <span class="text-red-500 font-bold">CLOSED</span></span>
        <span>Jamaah: <span class="text-red-500 font-bold">CLOSED</span></span>
      {% endif %}
          
    </div>
  </div>

    <!-- Asr card -->
    <div class="card md:card-side bg-base-100 shadow-xl max-h-[50px] w-full md:w-[250px] mb-2">
      <!-- Left Side: Image -->
      <figure class="max-w-[50px] max-h-[50px] bg-[#ff7f64] flex items-center justify-center">
        <img src="{% static 'images/sunset.png' %}" alt="fajr" class="w-full h-full object-cover" />
      </figure>
  
      <!-- Right Side: Text Content -->
      <div class="card-body pl-2 pt-1 leading-none">
        {% if today_schedule.open %}
          <span class="text-sm font-bold">Asr:<span id="T_Fajr text-xs">{{ asr }}</span></span>
          {% if today_schedule.asr_jamaah %}
            <span>Jamaah: {{ asr_j }}</span>
          {% else %}
            <span>Jamaah: <span class="text-red-500 font-bold">CLOSED</span></span>
          {% endif %}
        {% else %}
          <span class="text-sm font-bold">Asr: <span class="text-red-500 font-bold">CLOSED</span></span>
          <span>Jamaah: <span class="text-red-500 font-bold">CLOSED</span></span>
        {% endif %}
      </div>
    </div>
  
    <!-- maghrib card -->
    <div class="card md:card-side bg-base-100 shadow-xl max-h-[50px] w-full md:w-[250px] mb-2">
      <!-- Left Side: Image -->
      <figure class="max-w-[50px] max-h-[50px] bg-[#2980b9] flex items-center justify-center">
        <img src="{% static 'images/moonrise.png' %}" alt="fajr" class="w-full h-full object-cover" />
      </figure>
  
      <!-- Right Side: Text Content -->
      <div class="card-body pl-2 pt-1 leading-none">
        {% if today_schedule.open %}
          <span class="text-sm font-bold">Maghrib:<span id="T_Fajr text-xs">{{ maghrib }}</span></span>
          {% if today_schedule.maghrib_jamaah %}
            <span>Jamaah: {{ maghrib_j }}</span>
          {% else %}
            <span>Jamaah: <span class="text-red-500 font-bold">CLOSED</span></span>
          {% endif %}
        {% else %}
          <span class="text-sm font-bold">Maghrib: <span class="text-red-500 font-bold">CLOSED</span></span>
          <span>Jamaah: <span class="text-red-500 font-bold">CLOSED</span></span>
        {% endif %}
      </div>
    </div>

    <!-- Isha card -->
    <div class="card md:card-side bg-base-100 shadow-xl max-h-[50px] w-full md:w-[250px] mb-2">
      <!-- Left Side: Image -->
      <figure class="max-w-[50px] max-h-[50px] bg-[#99a3a4] flex items-center justify-center">
        <img src="{% static 'images/night.png' %}" alt="isha" class="w-full h-full object-cover" />
      </figure>
  
      <!-- Right Side: Text Content -->
      <div class="card-body pl-2 pt-1 leading-none">
        {% if today_schedule.open %}
          <span class="text-sm font-bold">Isha:<span id="T_Fajr text-xs">{{ isha }}</span></span>
          {% if today_schedule.isha_jamaah %}
            <span>Jamaah: {{ isha_j }}</span>
          {% else %}
            <span>Jamaah: <span class="text-red-500 font-bold">CLOSED</span></span>
          {% endif %}
        {% else %}
          <span class="text-sm font-bold">Isha: <span class="text-red-500 font-bold">CLOSED</span></span>
          <span>Jamaah: <span class="text-red-500 font-bold">CLOSED</span></span>
        {% endif %}
      </div>
    </div>

</div>

posts/templates/posts/partials/single_post.html
{% load static %}


    <li class="list-row" id="post{{post.id}}">
        <!-- Image Column -->
        <div>
            {% if post.image %}
                <img src="{{post.image.url}}" class="size-24 rounded-box">
            {% else %}
                <img src="{% static 'images/default_image.jpg' %}" class="size-24 rounded-box">
            {% endif %}
        </div>

        <!-- Content Column -->
        <div class="flex-1">
            <div>
                <h5 class="text-lg font-semibold">
                    <a href="{% url 'posts:post_view' post.id %}" class="hover:text-primary">{{post.title}}</a>
                </h5>
                <p class="text-sm">{{post.content|safe|truncatewords:30}}</p>
            </div>
            <div class="flex justify-between text-xs opacity-60">
                <div>{{post.published_date}}</div>
                {% if post.updated_date %}
                    <div>Last updated {{post.updated_date}}</div>
                {% endif %}
            </div>
        </div>

        <!-- Buttons Column -->
        <div class="flex flex-col gap-2">
            <!-- Publish/Unpublish Button -->
            <div id="publishButton{{post.id}}">
                {% if post.published %}
                    <button class="btn btn-warning btn-sm"
                        hx-post="{% url 'posts:post_toggle' post.id %}"
                        hx-target="#post{{post.id}}"
                    >
                        <i class="fa-solid fa-eye"></i> Unpublish
                    </button>
                {% else %}
                    <button class="btn btn-success btn-sm"
                        hx-post="{% url 'posts:post_toggle' post.id %}"
                        hx-target="#post{{post.id}}"
                    >
                        <i class="fa-solid fa-eye-slash"></i> Publish
                    </button>
                {% endif %}
            </div>

            <!-- Edit Button -->
            <a class="btn btn-warning btn-sm" href="{% url 'posts:post_edit' post.id %}">
                <i class="fa-solid fa-pen-to-square"></i> Edit
            </a>

            <!-- Delete Button -->
            <button class="btn btn-danger btn-sm"
                hx-delete="{% url 'posts:delete_post' post.id %}"
                hx-confirm="Are you sure you want to delete this post?"
                hx-target="#posts_list"
            >
                <i class="fa-solid fa-trash-can"></i> Delete
            </button>
        </div>
    </li>