core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include("masjidConfig.urls")),
    path('', include("posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

masjidConfig/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'masjidConfig'

urlpatterns = [
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('about/', views.about, name='about'),
]

posts/urls.py
from django.urls import path, include

from . import views
from .views import get_month_tbl
app_name = 'posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('monthly_times/', views.month_view, name='month_view'),
    path('post/<int:id>/', views.post_view, name='post_view'),
    path('posts-admin', views.posts_admin, name='posts_admin'),
    path('posts', views.post_list_view, name='post_list'),
    path('create_post', views.post_form, name='post_form'),
    path('post/<int:id>/delete/', views.delete_post, name='delete_post'),
    path('post/<int:id>/toggle', views.hide_post_toggle, name='post_toggle'),
    path('post/edit/<int:id>/', views.edit_post_form, name='post_edit'),
    path('pdf', views.GeneratePdf.as_view(), name="pdf"),
]

templates/base.html
{% load static %}

{% load masjid_tags %}
{% get_masjid as masjid_base %}
<html 
  {% if masjid_base.theme_choice %}
    data-theme="{{ masjid_base.theme_choice }}"
  {% else %}
    data-theme="light"
  {% endif %}>
    <head>
      <link href="https://cdn.jsdelivr.net/npm/daisyui@5.0.0-beta.8/daisyui.css" rel="stylesheet" type="text/css" />
      <link href="https://cdn.jsdelivr.net/npm/daisyui@5.0.0-beta.8/themes.css" rel="stylesheet" type="text/css" />
      <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
      {% block css %}{% endblock css %}
      <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>


    <body class="{% block bodyclass %}{% endblock bodyclass %}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        <div class="navbar bg-base-100 container mx-auto px-0 md:px-4 lg:px-8">
          <div class="navbar-start">
            <div class="dropdown">
              <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /> </svg>
              </div>
              <ul
                tabindex="0"
                class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow">
                  {% include 'nav_bar_links.html' %}
              </ul>
            </div>
            
            <a class="btn btn-ghost text-xl" href="{% url 'posts:home' %}">
              <img src="{{masjid_base.masjid_Logo.url}}" alt="" width="50" height="50">
            </a>
          </div>
          <div class="navbar-center hidden lg:flex">
            <ul class="menu menu-horizontal px-1">
              {% include 'nav_bar_links.html' %}
            </ul>
          </div>
          <div class="navbar-end">
            {% if user.is_authenticated %}
            <div class="dropdown dropdown-end">
              <!-- The navbar end button/icon -->
              <div tabindex="0" role="button" class="btn btn-ghost">
                <button type="button" class="btn btn-secondary" >Admin</button>
              </div>

              <!-- The dropdown menu -->
              <ul
              tabindex="0"
              class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow">
              <li><a class="" href="{% url 'posts:post_form' %}"><i class="fa-solid fa-plus"></i> Add Post</a></li>
              <div class="divider divider-secondary"></div>
              <li><a class="" href="{% url 'masjidConfig:edit_profile' %}">Edit Website Settings</a></li>
              <li><a class="" href="{% url 'posts:posts_admin' %}">Admin Posts</a></li>
              <div class="divider divider-secondary"></div>
              <li><a href="{% url 'logout' %}" class="btn btn-error">Logout</a></li>
            </ul>
          </div>

          {% else %}
            <form class="d-flex">
              <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
            </form>
          {% endif %}
          </div>
        </div>

          <div class="container mx-auto px-0 md:px-4 lg:px-8">{% block content %} {% endblock content %}</div>

          

          <div class="divider px-8"></div>


          <div class="bg-base-300">
            {% include 'footer.html' %}
          </div>
    </body>
    <script src="https://unpkg.com/htmx.org@1.7.0"></script>
</html>

templates/footer.html
{% load static %}

<footer class="footer sm:footer-horizontal bg-secondary p-10">
  <aside>
  <img src="{{masjid_base.masjid_Logo.url}}" alt="mosque logo" width="150">
    <p>
      <span class="text-xl">{{ masjid_base.masjid_Name }}</span>
      <br />
      {% if masjid_base.established %} Est {{ masjid_base.established |date:"Y"}} {% endif %}
    </p>
  </aside>

  <!-- Links section of the nav bar -->
  <nav>
    <h6 class="text-lg font-bold text-accent">Quick Links</h6>
    <a href="{% url 'posts:home' %}" class="link link-hover">Home</a>
    <a href="{% url 'posts:month_view'%}" class="link link-hover">Monthly Prayer Times</a>
    <a href="{% url 'posts:post_list'%}" class="link link-hover">Our Posts</a>
    <a href="{% url 'masjidConfig:about' %}" class="link link-hover">About</a>
  </nav>

  <!-- Social section of the navbar -->
  <nav>
    <h6 class="text-lg font-bold text-accent text-accent">Social</h6>
    <div class="grid grid-flow-col gap-4">
      {% include 'social_media_icons.html' %}      
    </div>
  </nav>
</footer>
<footer class="footer sm:footer-horizontal footer-center bg-base-300 text-base-content p-4">
  <aside>
    <p>
      <a href="https://openmosqueproject.com/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <img class="inline-block" src="{% static 'images/gsm_logo.png' %}" alt="" width="30" height="30">
      </a>
      <i class="fa-brands fa-creative-commons"></i>
      {% now "Y" %} - Open Mosque Project - <a href="https://openmosqueproject.com/">Get a free website for your mosque with us</a>
    </p>
  </aside>
</footer>

templates/nav_bar_links.html
<li class="">
    <a class="" href="{% url 'posts:home' %}">{{masjid_base.masjid_Name}} Home</a>
</li>
<li class="">
    <a class="" href="{% url 'posts:month_view'%}">Monthly Prayer Times</a>
</li>
<li class="">
    <a class="" href="{% url 'masjidConfig:about' %}">About us</a>
</li>

templates/social_media_icons.html
{% load static %}
{% if masjid_base.instagram %}
<a href="https://instagram.com/{{masjid.instagram}}">
    <i class="fa-brands fa-instagram fa-2xl text-accent"></i>
</a>
{% endif %}
{% if masjid_base.facebook %}
<a href="https://facebook.com/{{masjid.facebook}}">
    <i class="fa-brands fa-facebook fa-2xl text-accent"></i>
</a>
{% endif %}
{% if masjid_base.telegram %}
<a href="https://t.me/{{masjid.telegram}}">
    <i class="fa-brands fa-telegram fa-2xl text-accent"></i>
</a>
{% endif %}
{% if masjid_base.youtube %}
<a href="https://youtube.com/user/{{masjid.youtube}}">
    <i class="fa-brands fa-youtube fa-2xl text-accent"></i>
</a>
{% endif %}
{% if masjid_base.twitter %}
<a href="https://twitter.com/{{masjid.twitter}}">
    <i class="fa-brands fa-twitter fa-2xl text-accent"></i>
</a>
{% endif %}
{% if masjid_base.tiktok %}
<a href="https://www.tiktok.com/@{{masjid.tiktok}}">
    <i class="fa-brands fa-tiktok fa-2xl text-accent"></i>
</a>
{% endif %}