core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include("masjidConfig.urls")),
    path('', include("posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

posts/urls.py
from django.urls import path, include

from . import views
from .views import get_month_tbl
app_name = 'posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('monthly_times/', views.month_view, name='month_view'),
    path('post/<int:id>/', views.post_view, name='post_view'),
    path('posts-admin', views.posts_admin, name='posts_admin'),
    path('posts', views.post_list_view, name='post_list'),
    path('create_post', views.post_form, name='post_form'),
    path('post/<int:id>/delete/', views.delete_post, name='delete_post'),
    path('post/<int:id>/toggle', views.hide_post_toggle, name='post_toggle'),
    path('post/edit/<int:id>/', views.edit_post_form, name='post_edit'),
    path('pdf', views.GeneratePdf.as_view(), name="pdf"),
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import os

# Create your models here.
POST_CHOICES = [
    ('News', 'News'),
    ('Events', 'Events'),
    
]

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=1000) # RichTextField()
    type = models.CharField(max_length=200, choices=POST_CHOICES)
    published = models.BooleanField(default=False)
    published_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to='images/',
        processors=[ResizeToFill(800, 450)],
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.title
    
    def get_image_url(self):
        """Returns the image URL or falls back to default static image"""
        if self.image:
            return self.image.url
        return os.path.join(settings.STATIC_URL, 'images/default_image.jpg')

    def get_absolute_url(self, id=id or None):
        return reverse("posts:post_view", kwargs={'id':self.id})

posts/forms.py
from django.forms import ModelForm,widgets
from django.forms.widgets import TextInput, EmailInput
from .models import *
from django import forms


class PostForm(forms.ModelForm):
    content = forms.CharField() # widget=CKEditorWidget()
    class Meta:
        model = Post
        fields = '__all__'
    
    

posts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.views.generic import View 
from django.template.loader import get_template
from functools import lru_cache

from .utils import render_to_pdf

import requests, json, datetime
from .forms import PostForm
from .models import Post

from masjidConfig.models import CentreProfile

'''This function is used to round the time UP to the nearest 5,10,15
For more info, the idea is taken from 
https://stackoverflow.com/questions/13071384/ceil-a-datetime-to-next-quarter-of-an-hour
'''
def ceil_dt(dt, delta):
    return dt + (datetime.datetime.min - dt) % delta

''' The Jamaah Calculator function takes the desired "minutes after" from the masjid 
profile and adjusts the jamaah times accordingly by using Pythons datetime library.
'''
def jamaah_calculator(azaanTime, minutesAfter):

    if minutesAfter == "5":
        return datetime.datetime.strptime(azaanTime, '%H:%M') + datetime.timedelta(minutes = 5)
    elif minutesAfter == "10":
        return datetime.datetime.strptime(azaanTime, '%H:%M') + datetime.timedelta(minutes = 10)
    elif minutesAfter == "15":
        return datetime.datetime.strptime(azaanTime, '%H:%M') + datetime.timedelta(minutes = 15)
    elif minutesAfter == "round_to_fifteen":
        return ceil_dt(datetime.datetime.strptime(azaanTime, '%H:%M'), datetime.timedelta(minutes=15))
    else:
        return ceil_dt(datetime.datetime.strptime(azaanTime, '%H:%M'), datetime.timedelta(minutes=30))


@lru_cache(maxsize=1)
def get_masjid_data():
    masjid = CentreProfile.load()
    #### Variables loaded from centre profile here #####
    masjid_name = masjid.masjid_Name
    city = masjid.city 
    country = masjid.country 
    method = masjid.method
    longitude = masjid.longitude
    latitude = masjid.latitude
    current_time = datetime.datetime.now()
    month = current_time.month
    year = current_time.year
    fajr_jam_min = masjid.fajr_jamaah_minutes
    dh_jam_min = masjid.dhuhr_jamaah_minutes
    asr_jamaah_minutes = masjid.asr_jamaah_minutes
    maghrib_jamaah_minutes = masjid.maghrib_jamaah_minutes
    isha_jamaah_minutes = masjid.isha_jamaah_minutes
    return masjid, masjid_name,city, country, method, longitude, latitude, current_time, month, year, fajr_jam_min,dh_jam_min, asr_jamaah_minutes, maghrib_jamaah_minutes,isha_jamaah_minutes

# NOTE:
# Ternary statements below solves minutes being displayed as single digit eg
# 17:05 displaying as 17:5 or 20:00 displaying as 20:0
def home(request):
    # Collecting masjid data from class
    masjid, masjid_name,city, country, method, longitude, latitude, current_time, month, year, fajr_jam_min,dh_jam_min, asr_jamaah_minutes, maghrib_jamaah_minutes,isha_jamaah_minutes = get_masjid_data()
    ###############################################
    posts = Post.objects.all().filter(published=True)
    
    api_data = requests.get(f'http://api.aladhan.com/v1/timingsByCity?city={city}&country={country}&method={method}')
    d = api_data.json()
    fajr = d['data']['timings']['Fajr']
    fj = jamaah_calculator(fajr, fajr_jam_min)
    fjmins = f"{fj.minute}" if len(str(fj.minute))==2 else f"0{fj.minute}"
    fajr_j = f"{fj.hour}:{fjmins}"
    sunrise = d['data']['timings']['Sunrise']
    dhuhr = d['data']['timings']['Dhuhr']
    dh = jamaah_calculator(dhuhr, dh_jam_min)
    dhmins = f"{dh.minute}" if len(str(dh.minute))==2 else f"0{dh.minute}"
    dhuhr_j = f"{dh.hour}:{dhmins}"
    asr = d['data']['timings']['Asr']
    asrj = jamaah_calculator(asr, asr_jamaah_minutes)
    asmins = f"{asrj.minute}" if len(str(asrj.minute))==2 else f"0{asrj.minute}"
    asr_j= f"{asrj.hour}:{asmins}"
    maghrib = d['data']['timings']['Maghrib']
    mg = jamaah_calculator(maghrib, maghrib_jamaah_minutes)
    mgmins = f"{mg.minute}" if len(str(mg.minute))==2 else f"0{mg.minute}"
    maghrib_j =  f"{mg.hour}:{mgmins}"
    isha = d['data']['timings']['Isha']
    ish = jamaah_calculator(isha, isha_jamaah_minutes)
    ismins = f"{ish.minute}" if len(str(ish.minute))==2 else f"0{ish.minute}"
    isha_j= f"{ish.hour}:{ismins}"
    today = d['data']['date']['readable']
    hijri = f"{d['data']['date']['hijri']['day']}-{d['data']['date']['hijri']['month']['en']}-{d['data']['date']['hijri']['year']}"
    
    # Get today's day name (lowercase)
    today_day = current_time.strftime('%A').lower()
    weekly_schedule = masjid.weekly_schedule
    today_schedule = weekly_schedule.get(today_day, {
        'open': True,
        'fajr_jamaah': True,
        'dhuhr_jamaah': True,
        'asr_jamaah': True,
        'maghrib_jamaah': True,
        'isha_jamaah': True
    })
    
    context = {'masjid':masjid, 'posts':posts, 'fajr_j':fajr_j, 'dhuhr_j':dhuhr_j, 'asr_j':asr_j, 'maghrib_j':maghrib_j, 'isha_j':isha_j,
        'fajr':fajr,'sunrise':sunrise, 'dhuhr':dhuhr, 'asr':asr, 'maghrib':maghrib, 'isha':isha, 'today':today, 'hijri':hijri,
        'today_day':today_day, 'weekly_schedule':weekly_schedule, 'today_schedule':today_schedule}
    
    return render(request, 'posts/home.html', context)

def get_month_tbl():
    # Collecting masjid data from class
    masjid, masjid_name,city, country, method, longitude, latitude, current_time, month, year, fajr_jam_min,dh_jam_min, asr_jamaah_minutes, maghrib_jamaah_minutes,isha_jamaah_minutes = get_masjid_data()
    ###############################################
    month_api = requests.get(f'http://api.aladhan.com/v1/calendar?latitude={latitude}&longitude={longitude}&country={country}&method={method}&month={month}&year={year}')

    # Check if the request was successful
    if month_api.status_code != 200:
        raise Exception(f"API request failed with status code {month_api.status_code}")
    
    data = month_api.json()
    d = data['data']
    month_data = []
    weekly_schedule = masjid.weekly_schedule
    
    for row in d:
        date = row["date"]["gregorian"]["date"]
        weekday = row["date"]["gregorian"]["weekday"]["en"]
        weekday_lower = weekday.lower()
        mon = row["date"]["gregorian"]["month"]["en"]
        
        # Check if centre is open on this day
        day_schedule = weekly_schedule.get(weekday_lower, {})
        is_day_open = day_schedule.get('open', True)
        
        fajr = row["timings"]["Fajr"][0:5]
        sunrise = row["timings"]["Sunrise"][0:5]
        fj = jamaah_calculator(fajr, fajr_jam_min)
        fjmins = f"{fj.minute}" if len(str(fj.minute))==2 else f"0{fj.minute}"
        fajr_j = f"{fj.hour}:{fjmins}"
        
        dhuhr = row["timings"]["Dhuhr"][0:5]
        dh = jamaah_calculator(dhuhr, dh_jam_min)
        dhmins = f"{dh.minute}" if len(str(dh.minute))==2 else f"0{dh.minute}"
        dhuhr_j = f"{dh.hour}:{dhmins}"
        
        asr = row["timings"]["Asr"][0:5]
        asrj = jamaah_calculator(asr, asr_jamaah_minutes)
        asmins = f"{asrj.minute}" if len(str(asrj.minute))==2 else f"0{asrj.minute}"
        asr_j= f"{asrj.hour}:{asmins}"
        
        maghrib = row["timings"]["Maghrib"][0:5]
        mg = jamaah_calculator(maghrib, maghrib_jamaah_minutes)
        mgmins = f"{mg.minute}" if len(str(mg.minute))==2 else f"0{mg.minute}"
        maghrib_j =  f"{mg.hour}:{mgmins}"
        
        isha = row["timings"]["Isha"][0:5]
        ish = jamaah_calculator(isha, isha_jamaah_minutes)
        ismins = f"{ish.minute}" if len(str(ish.minute))==2 else f"0{ish.minute}"
        isha_j= f"{ish.hour}:{ismins}"
        
        day_no = row["date"]["gregorian"]["day"]
        day_ab = row["date"]["gregorian"]["weekday"]
        month_data.append({
            'fajr':fajr,'fajr_j':fajr_j,'sunrise':sunrise, 'dhuhr':dhuhr, 'dhuhr_j':dhuhr_j,'asr':asr,'asr_j':asr_j,'maghrib':maghrib,'maghrib_j':maghrib_j, 'isha':isha,'isha_j':isha_j,
            'month':mon, 'date':date, 'weekday':weekday,'day_no':day_no, 'day_ab':day_ab,
            'is_day_open': is_day_open,
            'fajr_jamaah': day_schedule.get('fajr_jamaah', True),
            'dhuhr_jamaah': day_schedule.get('dhuhr_jamaah', True),
            'asr_jamaah': day_schedule.get('asr_jamaah', True),
            'maghrib_jamaah': day_schedule.get('maghrib_jamaah', True),
            'isha_jamaah': day_schedule.get('isha_jamaah', True)
        })
    return month_data

def month_view(request):
    month_data = get_month_tbl()
    current_time = datetime.datetime.now()
    month_name = current_time.strftime("%B")
    year = current_time.year 
    context = {'d':json.dumps(month_data), 'month':month_name, 'year':year}
    return render(request, 'posts/month.html', context)

def post_view(request, id):
    post = Post.objects.get(id=id)
    context = {'post':post}
    return render(request, 'posts/post_view.html', context)

@login_required
def post_form(request): 
    form = PostForm(request.POST, request.FILES) 
    if form.is_valid():
        form.save()
        return redirect('posts:home')
    else:
        form = PostForm()
        context = {'form':form}
        return render(request, 'posts/post_form.html', context)

@login_required
def edit_post_form(request, id):
    post = get_object_or_404(Post, pk=id)
    
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('posts:post_view', kwargs={'id': id}))
        else:
            # Print form errors for debugging
            print("Form errors:", form.errors)
            context = {'form': form, 'post': post}
            return render(request, 'posts/post_edit_form.html', context)
    else:
        form = PostForm(instance=post)
        context = {'form': form, 'post': post}
        return render(request, 'posts/post_edit_form.html', context)

posts/templates/posts/month.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="px-4 py-5 my-5 text-center">
  <!-- Logo -->
  <img class="mx-auto mb-4 w-20 h-20" src="{{ masjid_base.masjid_Logo.url }}" alt="Masjid Logo">
  
  <!-- Title -->
  <h1 class="text-3xl font-bold mb-4">{{ masjid_base.masjid_Name|title }} Monthly Prayer Times for {{ month }} {{ year }}</h1>
  
  <!-- Print Button -->
  <div class="mt-6">
    <a href="{% url 'posts:pdf' %}" target="_blank" class="btn btn-primary btn-lg gap-3">
      <i class="fa-solid fa-print"></i> Print
    </a>
  </div>
</div>

<!-- Table Section -->
<div id="mytable" class="overflow-x-auto"></div>

<script>
  var obj = JSON.parse('{{ d | escapejs }}');
  var mytable = '<table class="table w-full text-center"><thead><tr><th scope="col"></th>';
mytable += '<tr>';
  mytable += '<th scope="col" rowspan="2"><i class="fa-solid fa-calendar-days"></i></th>'; // Day
  mytable += '<th scope="col" colspan="2">Fajr</th>'; // Fajr
  mytable += '<th scope="col" rowspan="2">Sunrise</th>'; // Sunrise
  mytable += '<th scope="col" colspan="2">Dhuhr</th>'; // Dhuhr
  mytable += '<th scope="col" colspan="2">Asr</th>'; // Asr
  mytable += '<th scope="col" colspan="2">Maghrib</th>'; // Maghrib
  mytable += '<th scope="col" colspan="2">Isha</th>'; // Isha
  mytable += '</tr>';

  // Sub-Headings Row
  mytable += '<tr>';
  mytable += '<th scope="col">Azan</th>'; // Fajr Azan
  mytable += '<th scope="col">Jamaah</th>'; // Fajr Jamaah
  mytable += '<th scope="col">Azan</th>'; // Dhuhr Azan
  mytable += '<th scope="col">Jamaah</th>'; // Dhuhr Jamaah
  mytable += '<th scope="col">Azan</th>'; // Asr Azan
  mytable += '<th scope="col">Jamaah</th>'; // Asr Jamaah
  mytable += '<th scope="col">Azan</th>'; // Maghrib Azan
  mytable += '<th scope="col">Jamaah</th>'; // Maghrib Jamaah
  mytable += '<th scope="col">Azan</th>'; // Isha Azan
  mytable += '<th scope="col">Jamaah</th>'; // Isha Jamaah
  mytable += '</tr>';
  mytable += '</thead><tbody>'; 

  var days_in_the_month = Object.keys(obj).length;
  var today = new Date();
  var today_formatted = today.getDate().toString();
  var today_date = today.getDate() + '-' + (today.getMonth() + 1) + '-' + today.getFullYear();
  if (today_formatted.length < 2) { today_formatted = '0' + today_formatted; }
  var month_formatted = (today.getMonth() + 1).toString();
  if (month_formatted.length < 2) { month_formatted = '0' + month_formatted; }
  var today_date_formatted = today_formatted + '-' + month_formatted + '-' + today.getFullYear();

  var tmonth = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
  var weekday = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  var month = tmonth[today.getMonth()];
  var bugun = weekday[today.getDay()];

  let newday = '';

  for (var i = 0; i < days_in_the_month; i++) {
    let day = (i + 1).toString();
    if (day.length < 2) { day = '0' + day; }

    var gun = day + '-' + month_formatted + '-' + today.getFullYear();
    var is_day_open = obj[i]['is_day_open'];
    
    // Azan times are always shown
    var fajr = obj[i]["fajr"];
    var sun = obj[i]['sunrise'];
    var dhu = obj[i]['dhuhr'];
    var asr = obj[i]['asr'];
    var mag = obj[i]['maghrib'];
    var ish = obj[i]['isha'];
    
    // Jamaah times show either the time or "CLOSED"
    var fajr_j = (is_day_open && obj[i]['fajr_jamaah']) ? obj[i]['fajr_j'] : '<span style="color: red; font-weight: bold;">CLOSED</span>';
    var dhu_j = (is_day_open && obj[i]['dhuhr_jamaah']) ? obj[i]['dhuhr_j'] : '<span style="color: red; font-weight: bold;">CLOSED</span>';
    var asr_j = (is_day_open && obj[i]['asr_jamaah']) ? obj[i]['asr_j'] : '<span style="color: red; font-weight: bold;">CLOSED</span>';
    var mag_j = (is_day_open && obj[i]['maghrib_jamaah']) ? obj[i]['maghrib_j'] : '<span style="color: red; font-weight: bold;">CLOSED</span>';
    var ish_j = (is_day_open && obj[i]['isha_jamaah']) ? obj[i]['isha_j'] : '<span style="color: red; font-weight: bold;">CLOSED</span>';

    var each_day = new Date(gun);
    var today_weekday = weekday[each_day.getDay()];

    if (obj[i]["date"] == today_date_formatted) {
      newday = `<tr class="bg-primary text-primary-content"><td>${day}</td><td>${fajr}</td><td>${fajr_j}</td><td>${sun}</td><td>${dhu}</td><td>${dhu_j}</td><td>${asr}</td><td>${asr_j}</td><td>${mag}</td><td>${mag_j}</td><td>${ish}</td><td>${ish_j}</td></tr>`;
    } else if (obj[i]["weekday"] == 'Friday') {
      newday = `<tr class="bg-warning text-warning-content"><td>${day}</td><td>${fajr}</td><td>${fajr_j}</td><td>${sun}</td><td>${dhu}</td><td>${dhu_j}</td><td>${asr}</td><td>${asr_j}</td><td>${mag}</td><td>${mag_j}</td><td>${ish}</td><td>${ish_j}</td></tr>`;
    } else {
      newday = `<tr><td>${day}</td><td>${fajr}</td><td>${fajr_j}</td><td>${sun}</td><td>${dhu}</td><td>${dhu_j}</td><td>${asr}</td><td>${asr_j}</td><td>${mag}</td><td>${mag_j}</td><td>${ish}</td><td>${ish_j}</td></tr>`;
    }
    mytable += newday;
  }
  mytable += "</tbody></table>";
  document.getElementById('mytable').innerHTML = mytable;
</script>

<script>
  function printFunction() { 
    window.print(); 
  }
</script>

  {% endblock content %}

posts/templates/posts/post_edit_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block css %}
    <!-- Include Quill stylesheet -->
  <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
  <!-- Include Quill library -->
  <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
{% endblock %}

{% block title %}Edit Post{% endblock %}
{% block content %}

{% if form.errors %}
    <div class="alert alert-error">
        <ul>
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<h1 class="text-2xl font-bold mb-4">Edit Post</h1>
<hr class="my-4">

<form action="{% url 'posts:post_edit' post.id %}" method="POST" enctype="multipart/form-data" class="space-y-4">
    {% csrf_token %}
    {{ form.media }}

    <!-- Title Field -->
    <div class="form-control">
        <label class="label">
            <span class="label-text">Title</span>
        </label>
        {{ form.title|add_class:"input input-bordered w-full" }}
        {% if form.title.errors %}
            <div class="text-error text-sm mt-1">
                {{ form.title.errors }}
            </div>
        {% endif %}
    </div>

    <!-- Content Field Rich text field -->
    <div class="form-control">
      <label class="label">
        <span class="label-text">Content</span>
      </label>
      <div id="editor" class="quill-editor">{{ form.content.value|safe }}</div>
      <textarea id="content" name="content" style="display: none;">{{ form.content.value|safe }}</textarea>
        {% if form.content.errors %}
          <div class="text-error text-sm mt-1">
              {{ form.content.errors }}
          </div>
        {% endif %}
    </div>

    <!-- Image Field -->
    <div class="form-control">
        <label class="label">
            <span class="label-text">Image</span>
        </label>
        {{ form.image|add_class:"file-input file-input-bordered w-full" }}
        {% if form.image.errors %}
            <div class="text-error text-sm mt-1">
                {{ form.image.errors }}
            </div>
        {% endif %}
    </div>

    <!-- Published Date Field -->
    <div class="form-control">
        <label class="label">
            <span class="label-text">Published Date</span>
        </label>
        {{ form.published_date|add_class:"input input-bordered w-full" }}
        {% if form.published_date.errors %}
            <div class="text-error text-sm mt-1">
                {{ form.published_date.errors }}
            </div>
        {% endif %}
    </div>

    <!-- Type Field -->
    <div class="form-control">
      <label class="label">
          <span class="label-text">Type</span>
      </label>
      {{ form.type|add_class:"select select-bordered w-full" }}
      {% if form.type.errors %}
          <div class="text-error text-sm mt-1">
              {{ form.type.errors }}
          </div>
      {% endif %}
    </div>

    <!-- Updated Date Field -->
    <div class="form-control">
        <label class="label">
            <span class="label-text">Updated Date</span>
        </label>
        {{ form.updated_date|add_class:"input input-bordered w-full" }}
        {% if form.updated_date.errors %}
            <div class="text-error text-sm mt-1">
                {{ form.updated_date.errors }}
            </div>
        {% endif %}
    </div>

    <!-- Published Checkbox -->
    <div class="form-control">
        <label class="label cursor-pointer">
            <span class="label-text">Published</span>
            {{ form.published|add_class:"checkbox checkbox-primary" }}
            {% if form.published.errors %}
              <div class="text-error text-sm mt-1">
                  {{ form.published.errors }}
              </div>
            {% endif %}
        </label>
    </div>
    
    <!-- Submit Button -->
    <div class="form-control">
        <input type="submit" class="btn btn-primary w-full" value="Submit" />
    </div>
</form>

<script src="{% static 'js/quill_editor_settings.js' %}"></script>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block css %}
    <!-- Include Quill stylesheet -->
  <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
  <!-- Include Quill library -->
  <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
{% endblock %}

{% block title %}Create Post{% endblock %}
{% block content %}

{% if form.errors %}
    <div class="alert alert-error">
        <ul>
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
<h1 class="text-2xl">Create Post Form</h1>
<br>

  <br><hr>
  
  <form action="{% url 'posts:post_form' %}" method="POST" enctype="multipart/form-data"> 
    {% csrf_token %}
    {{ form.media }}
    <!-- Title Field -->
    <div class="form-control">
      <label class="label">
          <span class="label-text">Title</span>
      </label>
      {{ form.title|add_class:"input input-bordered w-full" }}
      {% if form.title.errors %}
          <div class="text-error text-sm mt-1">
              {{ form.title.errors }}
          </div>
      {% endif %}
    </div>

    <!-- Content Field Rich text field -->
    <div class="form-control">
      <label class="label">
        <span class="label-text">Content</span>
      </label>
      <div id="editor" class="quill-editor">{{ form.content.value|safe }}</div>
      <textarea id="content" name="content" style="display: none;">{{ form.content.value|safe }}</textarea>
        {% if form.content.errors %}
          <div class="text-error text-sm mt-1">
              {{ form.content.errors }}
          </div>
        {% endif %}
    </div>

    <!-- Image Field -->
    <div class="form-control">
        <label class="label">
            <span class="label-text">Image</span>
        </label>
        {{ form.image|add_class:"file-input file-input-bordered w-full" }}
        {% if form.image.errors %}
            <div class="text-error text-sm mt-1">
                {{ form.image.errors }}
            </div>
        {% endif %}
    </div>

    <!-- Published Date Field -->
    <div class="form-control">
        <label class="label">
            <span class="label-text">Published Date</span>
        </label>
        {{ form.published_date|add_class:"input input-bordered w-full" }}
        {% if form.published_date.errors %}
            <div class="text-error text-sm mt-1">
                {{ form.published_date.errors }}
            </div>
        {% endif %}
    </div>

    <!-- Type Field -->
    <div class="form-control">
      <label class="label">
          <span class="label-text">Type</span>
      </label>
      {{ form.type|add_class:"select select-bordered w-full" }}
      {% if form.type.errors %}
          <div class="text-error text-sm mt-1">
              {{ form.type.errors }}
          </div>
      {% endif %}
    </div>

    <!-- Updated Date Field -->
    <div class="form-control">
        <label class="label">
            <span class="label-text">Updated Date</span>
        </label>
        {{ form.updated_date|add_class:"input input-bordered w-full" }}
        {% if form.updated_date.errors %}
            <div class="text-error text-sm mt-1">
                {{ form.updated_date.errors }}
            </div>
        {% endif %}
    </div>

    <!-- Published Checkbox -->
    <div class="form-control">
        <label class="label cursor-pointer">
            <span class="label-text">Published</span>
            {{ form.published|add_class:"checkbox checkbox-primary" }}
            {% if form.published.errors %}
              <div class="text-error text-sm mt-1">
                  {{ form.published.errors }}
              </div>
            {% endif %}
        </label>
    </div>
    
    <!-- Submit Button -->
    <div class="form-control">
        <input type="submit" class="btn btn-primary w-full" value="Submit" />
    </div>
  </form>

<script src="{% static 'js/quill_editor_settings.js' %}"></script>
{% endblock %}